name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  check-queue-available:
    name: Check whenever dev.pomu.app is not currently archiving
    runs-on: ubuntu-latest
    steps:
      - name: Check if any streams are currently being archived
        run: '! curl https://dev.pomu.app/api/queue | jq -r ".[] | select((.scheduledStart | fromdate < now) and (.finished == false))" | grep -q .'
  deploy:
    runs-on: ubuntu-latest
    needs: check-queue-available
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Setup `flyctl`"
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.58
      - name: Deploy to Dev
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
